#!name=TencentVideo Strong
#!desc=QX strong TencentVideo cleanup from 2026-05-26 capture.
#!author=zijinan
#!date=2026-05-26

^https?:\/\/(vv|vv6)\.video\.qq\.com\/getvinfo url script-request-body https://raw.githubusercontent.com/zijinan/Loon-rule/main/QuantumultX/script/TencentVideo-AntiCache.js
^https?:\/\/iacc\.qq\.com\/?$ url reject
^https?:\/\/iacc\.rec\.qq\.com\/?$ url reject
^https?:\/\/v3\.gdt\.qq\.com\/gdt_stats\.fcg url reject
^https?:\/\/rmonitor\.qq\.com\/ url reject
^https?:\/\/h\.trace\.qq\.com\/(kv|bosskv) url reject
^https?:\/\/trace\.inlong\.qq\.com\/ url reject
^https?:\/\/hc\.tdm\.qq\.com:8013\/ url reject-dict
^https?:\/\/receiver\.tdm\.qq\.com:8013\/ url reject-dict
^https?:\/\/szmg\.qq\.com\/(cgi-bin\/log_data\.fcg|heartbeat) url reject
^https?:\/\/api\.wuji\.qq\.com\/x\/api\/wuji_open\/object url reject-dict
^https?:\/\/cache\.wuji\.qq\.com\/ url reject-dict
^https?:\/\/tips\.video\.qq\.com\/device\/registerDevice url reject-dict
^https:\/\/i\.video\.qq\.com\/?$ url script-request-body https://raw.githubusercontent.com/zijinan/Loon-rule/main/QuantumultX/script/TencentVideo-AntiCache.js

hostname = vv.video.qq.com, vv6.video.qq.com, iacc.qq.com, iacc.rec.qq.com, v3.gdt.qq.com, rmonitor.qq.com, h.trace.qq.com, trace.inlong.qq.com, hc.tdm.qq.com, receiver.tdm.qq.com, szmg.qq.com, api.wuji.qq.com, cache.wuji.qq.com, tips.video.qq.com, i.video.qq.com
